--LAB 13 (IMPLEMENT ADVANCED LEVEL JOINS)

--PART – A: CREATE TABLE AS PER FOLLOWING DATA.


	--1. DISPLAY ALL THE VILLAGES OF RAJKOT CITY.

	--2. DISPLAY CITY ALONG WITH THEIR VILLAGES & PIN CODE.

	--3. DISPLAY THE CITY HAVING MORE THAN ONE VILLAGE.

	--4. DISPLAY THE CITY HAVING NO VILLAGE.

	--5. COUNT THE TOTAL NUMBER OF VILLAGES IN EACH CITY.

	--6. COUNT THE NUMBER OF CITIES HAVING MORE THAN ONE VILLAGE.

	--CREATE BELOW TABLE WITH FOLLOWING CONSTRAINTS

	--1. DO NOT ALLOW SPI MORE THAN 10

	--2. DO NOT ALLOW BKLOG LESS THAN 0.

	--3. ENTER THE DEFAULT VALUE AS ‘GENERAL’ IN BRANCH TO ALL NEW RECORDS IF NO OTHER VALUE IS SPECIFIED.

	--4. TRY TO UPDATE SPI OF RAJU FROM 8.80 TO 12.

	--5. TRY TO UPDATE BKLOG OF NEHA FROM 0 TO -1.


--PART – B: CREATE TABLE AS PER FOLLOWING SCHEMA WITH PROPER VALIDATION AND TRY TO INSERT DATA WHICH VIOLATE YOUR VALIDATION.


	--1. EMP_DETAILS(EID, ENAME, DID, CID, SALARY, EXPERIENCE)

		--DEPT_DETAILS(DID, DNAME)
		--CITY_DETAILS(CID, CNAME)


--PART – C: CREATE TABLE AS PER FOLLOWING SCHEMA WITH PROPER VALIDATION AND TRY TO INSERT DATA WHICH VIOLATE YOUR VALIDATION.


	--1. EMP_INFO(EID, ENAME, DID, CID, SALARY, EXPERIENCE)

		--DEPT_INFO(DID, DNAME)
		--CITY_INFO(CID, CNAME, DID))
		--DISTRICT(DID, DNAME, SID)
		--STATE(SID, SNAME, CID)
		--COUNTRY(CID, CNAME)

	--2. INSERT 5 RECORDS IN EACH TABLE.

	--3. DISPLAY EMPLOYEENAME, DEPARTMENTNAME, SALARY, EXPERIENCE, CITY, DISTRICT, STATE AND COUNTRY OF ALL EMPLOYEES.
