--LAB 10 (IMPLEMENT SQL VIEW)

--PART – A:

	--VIEWS (FIRST CREATE A VIEW THEN DISPLAY ALL VIEWS)


	--TABLE: STUDENT_INFO


		CREATE TABLE STUDENT_INFO (
			RNO INT,
			NAME VARCHAR(50),
			BRANCH VARCHAR(50),
			SPI DECIMAL(5, 2),
			BKLOG INT
		);

		INSERT INTO STUDENT_INFO (RNO, NAME, BRANCH, SPI, BKLOG) VALUES
		(101, 'RAJU', 'CE', 8.80, 0),
		(102, 'AMIT', 'CE', 2.20, 3),
		(103, 'SANJAY', 'ME', 1.50, 6),
		(104, 'NEHA', 'EC', 7.65, 1),
		(105, 'MEERA', 'EE', 5.52, 2),
		(106, 'MAHESH', 'EC', 4.50, 3);


		--TRUNCATE TABLE STUDENT_INFO
		SELECT * FROM STUDENT_INFO

	--1. CREATE A VIEW PERSONAL WITH ALL COLUMNS.
		CREATE VIEW PERSONAL 
		AS 
		SELECT * FROM STUDENT_INFO
		 	
	--2. CREATE A VIEW STUDENT_DETAILS HAVING COLUMNS NAME, BRANCH & SPI.
		CREATE VIEW STUDENT_DETAILS 
		AS 
		SELECT NAME,BRANCH,SPI FROM STUDENT_INFO

	--3. CREATE A VIEW ACADEMICDATA HAVING COLUMNS RNO, NAME, BRANCH.
		CREATE VIEW ACADEMICDATA 
		AS 
		SELECT RNO,NAME,BRANCH FROM STUDENT_INFO

	--4. CREATE A VIEW STUDENT_ BKLOG HAVING ALL COLUMNS BUT STUDENTS WHOSE BKLOG MORE THAN 2.
		CREATE VIEW STUDENT_BKLOG  
		AS 
		SELECT * FROM STUDENT_INFO
		WHERE BKLOG > 2

	--5. CREATE A VIEW STUDENT_PATTERN HAVING RNO, NAME & BRANCH COLUMNS IN WHICH NAME CONSISTS OF FOUR LETTERS.
		CREATE VIEW STUDENT_PATTERN  
		AS 
		SELECT RNO,NAME,BRANCH FROM STUDENT_INFO
		WHERE NAME LIKE '____'

	--6. INSERT A NEW RECORD TO ACADEMICDATA VIEW. (107, MEET, ME)
		INSERT INTO  ACADEMICDATA   
		SELECT 107,'MEET','ME'

		---OR---

		INSERT INTO  ACADEMICDATA   
		VALUES IN (107,'MEET','ME')
		

	--7. UPDATE THE BRANCH OF AMIT FROM CE TO ME IN STUDENT_DETAILS VIEW.
		UPDATE STUDENT_DETAILS 
		SET BRANCH = 'ME'
		WHERE NAME = 'AMIT'

	--8. DELETE A STUDENT WHOSE ROLL NUMBER IS 104 FROM ACADEMICDATA VIEW.
		DELETE FROM ACADEMICDATA
		WHERE RNO = 104


--PART – B:


	--1. CREATE A VIEW THAT DISPLAYS INFORMATION OF ALL STUDENTS WHOSE SPI IS ABOVE 8.5
		CREATE VIEW DISPLAY  
		AS 
		SELECT * FROM STUDENT_INFO
		WHERE SPI > 8.5

	--2. CREATE A VIEW THAT DISPLAYS 0 BACKLOG STUDENTS.
		CREATE VIEW DISPLAY_BKLOG 
		AS 
		SELECT * FROM STUDENT_INFO
		WHERE BKLOG = 0


	--3. CREATE A VIEW COMPUTERVIEW THAT DISPLAYS CE BRANCH DATA ONLY.
		CREATE VIEW COMPUTERVIEW  
		AS 
		SELECT * FROM STUDENT_INFO
		WHERE BRANCH = 'CE'


--PART – C:


	--1. CREATE A VIEW RESULT_EC THAT DISPLAYS THE NAME AND SPI OF STUDENTS WITH SPI LESS THAN 5 OF BRANCH EC.
		CREATE VIEW RESULT_EC  
		AS 
		SELECT NAME,SPI FROM STUDENT_INFO
		WHERE SPI < 5 AND BRANCH = 'EC' 

	--2. UPDATE THE RESULT OF STUDENT MAHESH TO 4.90 IN RESULT_EC VIEW.
		UPDATE  RESULT_EC
		SET SPI = 4.90
		WHERE NAME = 'MAHESH'


		--SELECT * FROM RESULT_EC


	--3. CREATE A VIEW STU_BKLOG WITH RNO, NAME AND BKLOG COLUMNS IN WHICH NAME STARTS WITH ‘M’ AND HAVING BKLOGS MORE THAN 5.
		CREATE VIEW STU_BKLOG  
		AS 
		SELECT RNO,NAME,BKLOG FROM STUDENT_INFO
		WHERE NAME LIKE 'M%' AND BKLOG > 5

	--4. DROP COMPUTERVIEW FORM THE DATABASE.
		DROP VIEW COMPUTERVIEW

