--LAB 12 (IMPLEMENT COMPLEX JOINS)

--CREATE FOLLOWING TABLE (USING DESIGN MODE)

		
CREATE TABLE DEPT (
    DepartmentID INT ,
    DepartmentName VARCHAR(100) ,
    DepartmentCode VARCHAR(50) ,
    Location VARCHAR(50) 
);

CREATE TABLE Person (
    PersonID INT PRIMARY KEY,
    PersonName VARCHAR(100) NOT NULL,
    DepartmentID INT NULL,
    Salary DECIMAL(8, 2) NOT NULL,
    JoiningDate DATETIME NOT NULL,
    City VARCHAR(100) NOT NULL,
    FOREIGN KEY (DepartmentID) REFERENCES Dept(DepartmentID)
);

INSERT INTO Dept (DepartmentID, DepartmentName, DepartmentCode, Location) VALUES
(1, 'Admin', 'Adm', 'A-Block'),
(2, 'Computer', 'CE', 'C-Block'),
(3, 'Civil', 'CI', 'G-Block'),
(4, 'Electrical', 'EE', 'E-Block'),
(5, 'Mechanical', 'ME', 'B-Block');

INSERT INTO Person (PersonID, PersonName, DepartmentID, Salary, JoiningDate, City) VALUES
(101, 'Rahul Tripathi', 2, 56000, '2000-01-01', 'Rajkot'),
(102, 'Hardik Pandya', 3, 18000, '2001-09-25', 'Ahmedabad'),
(103, 'Bhavin Kanani', 4, 25000, '2000-05-14', 'Baroda'),
(104, 'Bhoomi Vaishnav', 1, 39000, '2005-02-08', 'Rajkot'),
(105, 'Rohit Topiya', 2, 17000, '2001-07-23', 'Jamnagar'),
(106, 'Priya Menpara', NULL, 9000, '2000-10-18', 'Ahmedabad'),
(107, 'Neha Sharma', 2, 34000, '2002-12-25', 'Rajkot'),
(108, 'Nayan Goswami', 3, 25000, '2001-07-01', 'Rajkot'),
(109, 'Mehul Bhundiya', 4, 13500, '2005-01-09', 'Baroda'),
(110, 'Mohit Maru', 5, 14000, '2000-05-25', 'Jamnagar');



--FROM THE ABOVE GIVEN TABLE PERFORM THE FOLLOWING QUERIES:

--PART – A:

	--1. FIND ALL PERSONS WITH THEIR DEPARTMENT NAME & CODE.

	--2. FIND THE PERSON'S NAME WHOSE DEPARTMENT IS IN C-BLOCK.

	--3. RETRIEVE PERSON NAME, SALARY & DEPARTMENT NAME WHO BELONGS TO JAMNAGAR CITY.

	--4. RETRIEVE PERSON NAME, SALARY & DEPARTMENT NAME WHO DOES NOT BELONG TO RAJKOT CITY.

	--5. RETRIEVE PERSON’S NAME OF THE PERSON WHO JOINED THE CIVIL DEPARTMENT AFTER 1-AUG-2001.

	--6. FIND DETAILS OF ALL PERSONS WHO BELONG TO THE COMPUTER DEPARTMENT.

	--7. DISPLAY ALL THE PERSON'S NAME WITH THE DEPARTMENT WHOSE JOINING DATE DIFFERENCE WITH THE CURRENT DATE IS MORE THAN 365 DAYS.

	--8. FIND DEPARTMENT WISE PERSON COUNTS.

	--9. GIVE DEPARTMENT WISE MAXIMUM & MINIMUM SALARY WITH DEPARTMENT NAME.

	--10. FIND CITY WISE TOTAL, AVERAGE, MAXIMUM AND MINIMUM SALARY.

	--11. FIND THE AVERAGE SALARY OF A PERSON WHO BELONGS TO AHMEDABAD CITY.

	--12. PRODUCE OUTPUT LIKE: <PERSONNAME> LIVES IN <CITY> AND WORKS IN <DEPARTMENTNAME> DEPARTMENT. (IN SINGLE COLUMN)


--PART – B:


	--1. PRODUCE OUTPUT LIKE: <PERSONNAME> EARNS <SALARY> FROM <DEPARTMENTNAME> DEPARTMENT MONTHLY. (IN SINGLE COLUMN)

	--2. FIND CITY & DEPARTMENT WISE TOTAL, AVERAGE & MAXIMUM SALARIES.

	--3. FIND ALL PERSONS WHO DO NOT BELONG TO ANY DEPARTMENT.

	--4. FIND ALL DEPARTMENTS WHOSE TOTAL SALARY IS EXCEEDING 100000.

--PART – C:

	--1. LIST ALL DEPARTMENTS WHO HAVE NO PERSON.

	--2. LIST OUT DEPARTMENT NAMES IN WHICH MORE THAN TWO PERSONS ARE WORKING.

	--3. GIVE A 10% INCREMENT IN THE COMPUTER DEPARTMENT EMPLOYEE’S SALARY. (USE UPDATE)

