--LAB 2 (PERFORM SQL QUERIES FOR SELECT WITH OPERATORS)

--SELECT OPERATION

--PART – A:

	--FROM THE ABOVE GIVEN TABLES PERFORM THE FOLLOWING QUERIES:

	--1. RETRIEVE ALL DATA FROM TABLE DEPOSIT.

		SELECT * FROM DEPOSIT

	--2. RETRIEVE ALL DATA FROM TABLE BORROW.

		SELECT * FROM BORROW

	--3. RETRIEVE ALL DATA FROM TABLE CUSTOMERS.

		SELECT * FROM CUSTOMERS

	--4. DISPLAY ACCOUNT NO, CUSTOMER NAME & AMOUNT FROM DEPOSIT.

		SELECT  ACTNO,CNAME,AMOUNT FROM DEPOSIT

	--5. DISPLAY LOAN NO, AMOUNT FROM BORROW.

		SELECT  LOANNO,AMOUNT FROM BORROW

	--6. DISPLAY LOAN DETAILS OF ALL CUSTOMERS WHO BELONGS TO ‘ANDHERI’ BRANCH FROM BORROW TABLE.

		SELECT * FROM BORROW WHERE BNAME='ANDHERI'

	--7. GIVE ACCOUNT NO AND AMOUNT OF DEPOSITOR, WHOSE ACCOUNT NO IS EQUALS TO 106 FROM DEPOSIT TABLE.

		SELECT  ACTNO,AMOUNT FROM DEPOSIT WHERE ACTNO=106

	--8. GIVE NAME OF BORROWERS HAVING AMOUNT GREATER THAN 5000 FROM BORROW TABLE.
       
		SELECT CNAME FROM BORROW WHERE AMOUNT>5000

	--9. GIVE NAME OF CUSTOMERS WHO OPENED ACCOUNT AFTER DATE '1-12-96' FROM DEPOSIT TABLE.

		SELECT CNAME FROM DEPOSIT WHERE ADATE>'1996-12-1'

	--10. DISPLAY NAME OF CUSTOMERS WHOSE ACCOUNT NO IS LESS THAN 105 FROM DEPOSIT TABLE.

		SELECT CNAME FROM DEPOSIT WHERE ACTNO<105

	--11. DISPLAY NAME OF CUSTOMER WHO BELONGS TO EITHER ‘NAGPUR’ OR ‘DELHI’ FROM CUSTOMER TABLE. (OR & IN)

		SELECT CNAME FROM CUSTOMERS
		WHERE CITY ='NAGPUR'OR CITY ='DELHI'

		SELECT CNAME FROM CUSTOMERS 
		WHERE CITY IN ('NAGPUR','DELHI')

	--12. DISPLAY NAME OF CUSTOMERS WITH BRANCH WHOSE AMOUNT IS GREATER THAN 4000 AND ACCOUNT NO IS LESS THAN 105 FROM DEPOSIT TABLE.

		SELECT CNAME,BNAME FROM DEPOSIT WHERE AMOUNT>4000 AND ACTNO<105

	--13. FIND ALL BORROWERS WHOSE AMOUNT IS GREATER THAN EQUALS TO 3000 & LESS THAN EQUALS TO 8000 FROM BORROW TABLE. (AND & BETWEEN)

		SELECT * FROM BORROW WHERE AMOUNT>=3000 AND AMOUNT<8000

	--14. FIND ALL DEPOSITORS WHO DO NOT BELONGS TO ‘ANDHERI’ BRANCH FROM DEPOSIT TABLE.

		SELECT * FROM DEPOSIT WHERE BNAME<> 'ANDHERI'

	--15. DISPLAY ACCOUNT NO, CUSTOMER NAME & AMOUNT OF SUCH CUSTOMERS WHO BELONGS TO ‘AJNI’, ‘KAROLBAGH’ OR ‘M.G.ROAD’ AND ACCOUNT NO IS LESS THAN 104 FROM DEPOSIT TABLE.

		SELECT  ACTNO,CNAME,AMOUNT FROM DEPOSIT WHERE BNAME IN('AJNI','KAROLBAGH','M.G.ROAD') AND ACTNO<104

	
--PART – B:


	--1. DISPLAY ALL THE DETAILS OF FIRST FIVE CUSTOMERS FROM DEPOSIT TABLE.

		SELECT TOP 5* FROM DEPOSIT

	--2. DISPLAY ALL THE DETAILS OF FIRST THREE DEPOSITORS WHOSE AMOUNT IS GREATER THAN 1000.

		SELECT TOP 3* FROM DEPOSIT WHERE AMOUNT>1000

	--3. DISPLAY LOAN NO, CUSTOMER NAME OF FIRST FIVE BORROWERS WHOSE BRANCH NAME DOES NOT BELONGS TO ‘ANDHERI’ FROM BORROW TABLE.

		SELECT TOP 5 LOANNO,CNAME FROM BORROW WHERE BNAME!='ANDHERI'  

	--4. RETRIEVE ALL UNIQUE CITIES USING DISTINCT. (USE CUSTOMERS TABLE)

		SELECT DISTINCT CNAME FROM CUSTOMERS

	--5. RETRIEVE ALL UNIQUE BRANCHES USING DISTINCT. (USE BRANCH TABLE)

		SELECT DISTINCT BNAME FROM BRANCH



--	PART – C:

	--1. RETRIEVE TOP 50% RECORD FROM TABLE BORROW.

		SELECT TOP 50 PERCENT * FROM BORROW

	--2. DISPLAY TOP 10% AMOUNT FROM TABLE DEPOSIT.

		SELECT TOP 10 PERCENT AMOUNT FROM DEPOSIT

	--3. DISPLAY TOP 25% CUSTOMER WHO DEPOSITED MORE THAN 5000.

		SELECT TOP 25 PERCENT *  FROM DEPOSIT 
		WHERE AMOUNT>5000

	--4. RETRIEVE FIRST 10% LOAN AMOUNTS.

		SELECT TOP 10 PERCENT AMOUNT FROM BORROW

	--5. RETRIEVE ALL UNIQUE CUSTOMER NAMES WITH CITY.

		SELECT DISTINCT CNAME,CITY FROM CUSTOMERS

	--6. RETRIEVE ALL LOAN RECORDS WITH ONE MORE COLUMN IN LOAN AMOUNT AS 10% EXTRA AMOUNT.

		SELECT  (AMOUNT*1.1) AS 'EXTRA_AMOUNT' FROM BORROW

	--7. RETRIEVE ALL ODD/EVEN VALUE LOAN NUMBER FROM BORROW TABLE.

		SELECT LOANNO  AS 'ODD_VALUE' FROM BORROW WHERE (LOANNO%2!=0) 

		SELECT LOANNO  AS 'EVEN_VALUE' FROM BORROW WHERE (LOANNO%2=0)