--LAB 3 (PERFORM SQL QUERIES FOR SELECT INTO AND UPDATE)

--SELECT INTO OPERATION

--PART – A: 

		CREATE TABLE CRICKET
		(
			NAME VARCHAR(50),
			CITY VARCHAR(50),
			AGE INT
		);

		INSERT INTO CRICKET(NAME,CITY,AGE) VALUES('SCAHIN TENDULKAR','MUMBAI',30),
		('RAHUL DRAVID','BOMBAY', 35),
		('M. S. DHONI' ,'JHARKHAND' ,31),
		('SURESH RAINA' ,'GUJARAT' ,30)


		SELECT * FROM CRICKET

	-- PART A

	--1. CREATE TABLE WORLDCUP FROM CRICKET WITH ALL THE COLUMNS AND DATA.
		SELECT * INTO WORLDCUP FROM CRICKET 
	

	--2. CREATE TABLE T20 FROM CRICKET WITH FIRST TWO COLUMNS WITH NO DATA.
		SELECT NAME,CITY INTO T20 FROM CRICKET WHERE 1=2

	--3. CREATE TABLE IPL FROM CRICKET WITH NO DATA
		SELECT * INTO IPL WHERE 1=2


--PART – B:

		CREATE TABLE EMPLOYEE
			(
				NAME VARCHAR(50),
				CITY VARCHAR(50),
				AGE INT
			);	

		INSERT INTO EMPLOYEE(NAME,CITY,AGE) VALUES 
				('JAY PATEL','RAJKOT', 30),
				('RAHUL DAVE' ,'BARODA' ,35),
				('JEET PATEL' ,'SURAT' ,31),
				('VIJAY RAVAL' ,'RAJKOT' ,30)

		SELECT * FROM EMPLOYEE		

	--1. CREATE TABLE EMPLOYEE_DETAIL FROM EMPLOYEE WITH ALL THE COLUMNS AND DATA.

		SELECT * INTO EMPLOYEE_DETAIL FROM EMPLOYEE
		--DELETE FROM EMPLOYEE_DETAIL
		SELECT * FROM EMPLOYEE_DETAIL
	
	--2. CREATE TABLE EMPLOYEE_DATA FROM EMPLOYEE WITH FIRST TWO COLUMNS WITH NO DATA.

		SELECT NAME,CITY INTO EMPLOYEE_DATA FROM EMPLOYEE 
		SELECT * FROM EMPLOYEE_DATA

	--3. CREATE TABLE EMPLOYEE_INFO FROM EMPLOYEE WITH NO DATA

		SELECT * INTO EMPLOYEE_INFO FROM EMPLOYEE WHERE 1=2
		SELECT *  FROM EMPLOYEE_INFO
	

--	PART – C:

	--PERFORM FOLLOWING QUERIES ON EMPLOYEE TABLE.

	--1. INSERT THE DATA INTO EMPLOYEE_INFO FROM EMPLOYEE WHOSE CITY IS RAJKOT

		INSERT INTO EMPLOYEE_INFO
		SELECT * FROM EMPLOYEE
		WHERE CITY = 'RAJKOT'

	--2. INSERT THE DATA INTO EMPLOYEE_INFO FROM EMPLOYEE WHOSE AGE IS MORE THAN 32.

		INSERT INTO EMPLOYEE_INFO
		SELECT * FROM EMPLOYEE
		WHERE AGE>32


--UPDATE OPERATION

--PART – A: 

	--1. UPDATE DEPOSIT AMOUNT OF ALL CUSTOMERS FROM 3000 TO 5000. (USE DEPOSIT TABLE)

		UPDATE DEPOSIT SET AMOUNT=5000 WHERE AMOUNT=3000

	--2. CHANGE BRANCH NAME OF ANIL FROM VRCE TO C.G. ROAD. (USE BORROW TABLE)

		UPDATE BORROW SET BNAME='C.G.ROAD' WHERE CNAME='ANIL' AND BNAME='VRCE'

	--3. UPDATE ACCOUNT NO OF SANDIP TO 111 & AMOUNT TO 5000. (USE DEPOSIT TABLE)

		UPDATE DEPOSIT SET ACTNO=111,AMOUNT=5000 WHERE ACTNO=106  AND AMOUNT=2000  

	--4. UPDATE AMOUNT OF KRANTI TO 7000. (USE DEPOSIT TABLE)

		UPDATE DEPOSIT SET AMOUNT=7000 WHERE CNAME='KRANTI'

	--5. UPDATE BRANCH NAME FROM ANDHERI TO ANDHERI WEST. (USE BRANCH TABLE)

		UPDATE BRANCH SET  BNAME='WEST ANDHERI' WHERE BNAME='ANDHERI'

	--6. UPDATE BRANCH NAME OF MEHUL TO NEHRU PALACE. (USE DEPOSIT TABLE)

		UPDATE DEPOSIT SET BNAME='NEHRU PALACE' WHERE CNAME='MEHUL'

	--7. UPDATE DEPOSIT AMOUNT OF ALL DEPOSITORS TO 5000 WHOSE ACCOUNT NO BETWEEN 103 & 107. (USE DEPOSIT TABLE)

		UPDATE DEPOSIT SET AMOUNT=5000 WHERE ACTNO BETWEEN 103 AND 107

	--8. UPDATE ADATE OF ANIL TO 1-4-95. (USE DEPOSIT TABLE)

		UPDATE DEPOSIT SET ADATE='1995-4-1' WHERE CNAME='ANIL'

	--9. UPDATE THE AMOUNT OF MINU TO 10000. (USE DEPOSIT TABLE)

		UPDATE DEPOSIT SET AMOUNT=10000 WHERE CNAME='MINU'

	--10. UPDATE DEPOSIT AMOUNT OF PRAMOD TO 5000 AND ADATE TO 1-4-96 (USE DEPOSIT TABLE)

		UPDATE DEPOSIT SET AMOUNT=5000,ADATE='1996-4-1' WHERE CNAME='PRAMOD'


--	PART – B:



	--1. GIVE 10% INCREMENT IN LOAN AMOUNT. (USE BORROW TABLE)

		UPDATE BORROW
		SET AMOUNT = (AMOUNT+AMOUNT*0.1)
	
	--2. CUSTOMER DEPOSITS ADDITIONAL 20% AMOUNT TO THEIR ACCOUNT, UPDATE THE SAME. (USE DEPOSIT TABLE)

		UPDATE  DEPOSIT
		SET AMOUNT = (AMOUNT*1.2)


--PART – C:



	--1. UPDATE AMOUNT OF LOAN NO 321 TO NULL. (USE BORROW TABLE)

		UPDATE BORROW 
		SET AMOUNT = NULL 
		WHERE LOANNO = 321

	--2. UPDATE BRANCH NAME OF KRANTI TO NULL (USE BORROW TABLE)

		UPDATE BORROW
		SET BNAME = NULL 
		WHERE CNAME = 'KRANTI'

	--3. DISPLAY THE NAME OF BORROWERS WHOSE AMOUNT IS NULL. (USE BORROW TABLE)

		SELECT CNAME FROM BORROW WHERE AMOUNT IS NULL

	--4. DISPLAY THE BORROWERS WHOSE HAVING BRANCH. (USE BORROW TABLE)

		SELECT CNAME,BNAME FROM BORROW WHERE BNAME IS NOT NULL

	--5. UPDATE THE LOAN AMOUNT TO 5000, BRANCH TO VRCE & CUSTOMER NAME TO DARSHAN WHOSE LOAN NO IS 481.(USE BORROW TABLE)

		UPDATE BORROW 
		SET AMOUNT = 5000,BNAME = 'VRCE',CNAME = 'DARSHAN'
		WHERE LOANNO = 481

	--6. UPDATE THE DEPOSIT TABLE AND SET THE DATE TO 01-01-2021 FOR ALL THE DEPOSITOR WHOSE AMOUNT IS LESS THAN 2000.

		UPDATE DEPOSIT
		SET ADATE = '01-01-2021'
		WHERE AMOUNT<2000

	--7. UPDATE THE DEPOSIT TABLE AND SET THE DATE TO NULL & BRANCH NAME TO ‘ANDHERI WHOSE ACCOUNT NO IS 110.

		UPDATE DEPOSIT 
		SET ADATE = NULL ,BNAME = 'ANDHERI'
		WHERE ACTNO = 110
