--LAB 4 (PERFORM SQL QUERIES FOR ALTER, DELETE, TRUNCATE, AND DROP)

--ALTER OPERATION

--PART – A:

	--FROM THE ABOVE GIVEN TABLES PERFORM THE FOLLOWING QUERIES (ALTER OPERATION):

	--1. ADD TWO MORE COLUMNS CITY VARCHAR (20) AND PINCODE INT.

		ALTER TABLE DEPOSIT ADD CITY VARCHAR(20),PINCODE INT

	--2. CHANGE THE SIZE OF CNAME COLUMN FROM VARCHAR (50) TO VARCHAR (35).

		ALTER TABLE DEPOSIT ALTER COLUMN CNAME VARCHAR(35)

	--3. CHANGE THE DATA TYPE DECIMAL TO INT IN AMOUNT COLUMN.

		ALTER TABLE DEPOSIT ALTER COLUMN AMOUNT INT

	--4. RENAME COLUMN ACTNO TO ANO.

		SP_RENAME 'DEPOSIT.ACTNO','ANO'

	--5. DELETE COLUMN CITY FROM THE DEPOSIT TABLE.

		ALTER TABLE DEPSOIT DROP COLUMN CITY

	--6. CHANGE NAME OF TABLE DEPOSIT TO DEPOSIT_DETAIL.

		SP_RENAME 'DEPOSIT','DEPOSIT_DETAIL'


--PART – B:

	--1. RENAME COLUMN ADATE TO AOPENDATE OF DEPOSIT_DETAIL TABLE.

		SP_RENAME 'DEPOSIT_DETAIL.ADATE','AOPENDATE'

	--2. DELETE COLUMN AOPENDATE FROM THE DEPOSIT_DETAIL TABLE.

		ALTER TABLE DEPOSIT_DETAIL DROP COLUMN AOPENDATE

	--3. RENAME COLUMN CNAME TO CUSTOMERNAME

		SP_RENAME 'DEPOSIT_DETAIL.CNAME','CUSTOMERNAME'



--PART – C:

	CREATE TABLE STUDENT_DETAIL(
	
			ENROLLMENT_NO VARCHAR(20),
			NAME VARCHAR(25),
			CPI DECIMAL(8,2),
			BIRTHDATE DATETIME
			);

			SELECT * FROM STUDENT_DETAIL


	--1. ADD TWO MORE COLUMNS CITY VARCHAR (20) (NOT NULL) AND BACKLOG INT (NULL).
		ALTER TABLE STUDENT_DETAIL
		ADD CITY VARCHAR(20) NOT NULL DEFAULT 'RAJKOT',
		BACKLOG INT  NOT NULL IDENTITY(1,1)

	--2. CHANGE THE SIZE OF NAME COLUMN OF STUDENT_DETAIL FROM VARCHAR (25) TO VARCHAR (35).
		ALTER TABLE STUDENT_DETAIL ALTER COLUMN NAME VARCHAR(35) 

	--3. CHANGE THE DATA TYPE DECIMAL TO INT IN CPI COLUMN.
		ALTER TABLE STUDENT_DETAIL ALTER COLUMN CPI INT

	--4. RENAME COLUMN ENROLLMENT_NO TO ENO.
		SP_RENAME 'STUDENT_DETAIL.ENROLLMENT_NO','ENO'

	--5. DELETE COLUMN CITY FROM THE STUDENT_DETAIL TABLE.
		ALTER TABLE STUDENT_DETAIL DROP COLUMN CITY

	--6. CHANGE NAME OF TABLE STUDENT_DETAIL TO STUDENT_MASTER.
		SP_RENAME 'STUDENT_DETAIL','STUDENT_MASTER'


--DELETE, TRUNCATE, DROP OPERATION	

--PART – A:

	--1. DELETE ALL THE RECORDS OF DEPOSIT_DETAIL TABLE HAVING AMOUNT GREATER THAN AND EQUALS TO 4000.
	DELETE FROM DEPOSIT_DETAIL WHERE AMOUNT>=4000

	--2. DELETE ALL THE ACCOUNTS CHANDI BRANCH.
	DELETE FROM DEPOSIT_DETAIL WHERE BNAME='CHANDI'

	--3. DELETE ALL THE ACCOUNTS HAVING ACCOUNT NUMBER (ANO) IS GREATER THAN 105.
	DELETE FROM DEPOSIT_DETAIL WHERE ANO>105

	--4. DELETE ALL THE RECORDS OF DEPOSIT_DETAIL TABLE. (USE TRUNCATE)
	TRUNCATE TABLE DEPOSIT_DETAIL

	--5. REMOVE DEPOSIT_DETAIL TABLE. (USE DROP)
	DROP TABLE DEPOSIT_DETAIL

	SELECT * FROM DEPOSIT_DETAIL

--PART – B:

			CREATE TABLE EMPLOYEE_MASTER
			(
				EMPNO INT,
				EMPNAME VARCHAR(25),
				JOININGDATE DATETIME,
				SALARY DECIMAL(8,2),
				CITY VARCHAR(20)
			);

			INSERT INTO EMPLOYEE_MASTER VALUES(101,'KEYUR','2002-1-5',12000,'RAJKOT')
			INSERT INTO EMPLOYEE_MASTER VALUES(102,'HARDIK','2004-2-15',14000,'AHMEDABAD')
			INSERT INTO EMPLOYEE_MASTER VALUES(103,'KAJAL','2006-3-14',15000,'BARODA')
			INSERT INTO EMPLOYEE_MASTER VALUES(104,'BHOOMI','2005-6-23',12500,'AHMEDABAD')
			INSERT INTO EMPLOYEE_MASTER VALUES(105,'HARMIT','2004-2-15',14000,'RAJKOT')
			INSERT INTO EMPLOYEE_MASTER VALUES(106,'MITESH','2001-9-25',5000,'JAMNAGAR')
			INSERT INTO EMPLOYEE_MASTER VALUES(107,'MEERA',NULL,7000,'MORBI')
			INSERT INTO EMPLOYEE_MASTER VALUES(108,'KISHAN','2003-2-6',10000,NULL)
		

			SELECT * FROM EMPLOYEE_MASTER

	--1. DELETE ALL THE RECORDS OF EMPLOYEE_MASTER TABLE HAVING SALARY GREATER THAN AND EQUALS TO 14000.

		DELETE FROM EMPLOYEE_MASTER
		WHERE SALARY>=14000

	--2. DELETE ALL THE EMPLOYEES WHO BELONGS TO ‘RAJKOT’ CITY.

		DELETE FROM	EMPLOYEE_MASTER
		WHERE CITY='RAJKOT'

	--3. DELETE ALL THE EMPLOYEES WHO JOINED AFTER 1-1-2007.

		DELETE FROM	EMPLOYEE_MASTER
		WHERE JOININGDATE > '2007-1-1'

	--4. DELETE THE RECORDS OF EMPLOYEES WHOSE JOINING DATE IS NULL AND NAME IS NOT NULL.

		DELETE FROM EMPLOYEE_MASTER
		WHERE JOININGDATE = NULL AND EMPNAME IS NOT NULL
 
	--5. DELETE THE RECORDS OF EMPLOYEES WHOSE SALARY IS 50% OF 20000.

		DELETE FROM EMPLOYEE_MASTER
		WHERE SALARY = 2000*0.5

	--6. DELETE THE RECORDS OF EMPLOYEES WHOSE CITY NAME IS NOT EMPTY.

		DELETE FROM EMPLOYEE_MASTER
		WHERE CITY IS NOT NULL

	--7. DELETE ALL THE RECORDS OF EMPLOYEE_MASTER TABLE. (USE TRUNCATE)

		TRUNCATE TABLE EMPLOYEE_MASTER

	--8. REMOVE EMPLOYEE_MASTER TABLE. (USE DROP)

		DROP TABLE EMPLOYEE_MASTER


--PART – C:

		--1. SUMMARIZE DELETE, TRUNCATE AND DROP
			-- GO THROUGH PPT

	---- {'"JIG''S HOME",NAROL'}




