--LAB5 PERFORM SQL QUERIES FOR LIKE OPERATOR

--PART – A:

	--CREATE FOLLOWING TABLE USING QUERY ACCORDING TO THE DEFINITION

	CREATE TABLE STUDENT
	(
		STUID INT,
		FIRSTNAME VARCHAR(25),
		LASTNAME VARCHAR(25),
		WEBSITE VARCHAR(50),
		CITY VARCHAR(25),
		ADDRESS VARCHAR(100)
	);

	INSERT INTO STUDENT VALUES(1011,'KEYUR','PATEL','TECHNOHENET.COM','RAJKOT','A-303 ''VASANT KUNJ'',RAJKOT')
	INSERT INTO STUDENT VALUES(1022,'HARDIK','SHAH','DIGMINECRAFT.COM','AHMEDABAD','"RAM KRUPA", RAIYA ROAD')
	INSERT INTO STUDENT VALUES(1033,'KAJAL','TRIVEDI','BIGACTIVITIES.COM','BARODA','RAJ BHAVAN PLOT, NEAR GARDEN')
	INSERT INTO STUDENT VALUES(1044,'BHOOMI','GAJERA','CHEKYOURMATH.COM','AHMEDABAD','"JIG''S HOME", NAROL')
	INSERT INTO STUDENT VALUES(1055,'HARMIT','MITEL','@ME.DARSHAN.COM','RAJKOT','B-55,RAJ RESIDENCY')
	INSERT INTO STUDENT VALUES(1066,'ASHOK','JANI',NULL,'BARODA','A502, CLUB HOUSE BUILDING')

	SELECT * FROM STUDENT

	--FROM THE ABOVE GIVEN TABLES PERFORM THE FOLLOWING QUERIES (LIKE OPERATION):

	--1. DISPLAY THE NAME OF STUDENTS WHOSE NAME STARTS WITH ‘K’.
		SELECT FIRSTNAME FROM STUDENT
		WHERE FIRSTNAME LIKE 'K%'

	--2. DISPLAY THE NAME OF STUDENTS WHOSE NAME CONSISTS OF FIVE CHARACTERS.
		SELECT FIRSTNAME FROM STUDENT
		WHERE FIRSTNAME LIKE '_____'

	--3. RETRIEVE THE FIRST NAME & LAST NAME OF STUDENTS WHOSE CITY NAME ENDS WITH A & CONTAINS SIX CHARACTERS.
		SELECT FIRSTNAME FROM STUDENT
		WHERE CITY LIKE '_____A'  

	--4. DISPLAY ALL THE STUDENTS WHOSE LAST NAME ENDS WITH ‘TEL’.
		SELECT * FROM STUDENT
		WHERE FIRSTNAME LIKE '%TEL'

	--5. DISPLAY ALL THE STUDENTS WHOSE FIRST NAME STARTS WITH ‘HA’ & ENDS WITH‘T’.
		SELECT * FROM STUDENT
		WHERE FIRSTNAME LIKE 'HA%T'


	--6. DISPLAY ALL THE STUDENTS WHOSE FIRST NAME STARTS WITH ‘K’ AND THIRD CHARACTER IS ‘Y’.
		SELECT FIRSTNAME FROM STUDENT
		WHERE FIRSTNAME LIKE 'K_Y%'

	--7. DISPLAY THE NAME OF STUDENTS HAVING NO WEBSITE AND NAME CONSISTS OF FIVE CHARACTERS.
		SELECT FIRSTNAME FROM STUDENT
		WHERE WEBSITE IS NULL AND FIRSTNAME LIKE '_____'

	--8. DISPLAY ALL THE STUDENTS WHOSE LAST NAME CONSIST OF ‘JER’.
		SELECT * FROM STUDENT
		WHERE FIRSTNAME LIKE '%JER%'

	--9. DISPLAY ALL THE STUDENTS WHOSE CITY NAME STARTS WITH EITHER ‘R’ OR ‘B’.
		SELECT * FROM STUDENT
		WHERE FIRSTNAME LIKE '[RB]%'

	--10. DISPLAY ALL THE NAME STUDENTS HAVING WEBSITES.
		SELECT * FROM STUDENT
		WHERE WEBSITE IS NOT NULL 

	--11. DISPLAY ALL THE STUDENTS WHOSE NAME STARTS FROM ALPHABET A TO H.
		SELECT * FROM STUDENT
		WHERE FIRSTNAME LIKE '[A-H]%'

	--12. DISPLAY ALL THE STUDENTS WHOSE NAME’S SECOND CHARACTER IS VOWEL.
		SELECT * FROM STUDENT
		WHERE FIRSTNAME LIKE '_[AEIOU]%'

	--13. DISPLAY THE NAME OF STUDENTS HAVING NO WEBSITE AND NAME CONSISTS OF MINIMUM FIVE CHARACTERS.
		SELECT * FROM STUDENT
		WHERE FIRSTNAME LIKE '______%'

	--14. DISPLAY ALL THE STUDENTS WHOSE LAST NAME STARTS WITH ‘PAT’.
		SELECT * FROM STUDENT
		WHERE FIRSTNAME LIKE 'PAT%'

	--15. DISPLAY ALL THE STUDENTS WHOSE CITY NAME DOES NOT STARTS WITH ‘B’.
		SELECT * FROM STUDENT
		WHERE FIRSTNAME  NOT LIKE 'B%'

--PART – B:

	--1. DISPLAY ALL THE STUDENTS WHOSE NAME STARTS FROM ALPHABET A OR H.
		SELECT * FROM STUDENT
		WHERE FIRSTNAME LIKE '[AH]%'

	--2. DISPLAY ALL THE STUDENTS WHOSE NAME’S SECOND CHARACTER IS VOWEL AND OF AND START WITH H.
		SELECT * FROM STUDENT
		WHERE FIRSTNAME LIKE 'H[AEIOU]%'

	--3. DISPLAY ALL THE STUDENTS WHOSE LAST NAME DOES NOT ENDS WITH ‘A’.
		SELECT * FROM STUDENT
		WHERE FIRSTNAME  NOT LIKE '%A'

	--4. DISPLAY ALL THE STUDENTS WHOSE FIRST NAME STARTS WITH CONSONANT.
		SELECT * FROM STUDENT
		WHERE FIRSTNAME NOT LIKE '[AEIOU]%'

	--5. DISPLAY ALL THE STUDENTS WHOSE WEBSITE CONTAINS .NET
		SELECT * FROM STUDENT
		WHERE FIRSTNAME LIKE '%.NET%'

--PART – C:

	--1. DISPLAY ALL THE STUDENTS WHOSE ADDRESS CONSIST OF -.
		SELECT * FROM STUDENT
		WHERE ADDRESS LIKE '%-%'

	--2. DISPLAY ALL THE STUDENTS WHOSE ADDRESS CONTAINS SINGLE QUOTE OR DOUBLE QUOTE.
		SELECT * FROM STUDENT
		WHERE ADDRESS LIKE '%''%' OR ADDRESS LIKE '%"%'

		SELECT * FROM STUDENT
		WHERE ADDRESS LIKE '%''%''%' 

	--3. DISPLAY ALL THE STUDENTS WHOSE WEBSITE CONTAINS @.
		SELECT * FROM STUDENT
		WHERE WEBSITE LIKE '%@%'

	--4. DISPLAY ALL THE NAMES THOSE ARE EITHER FOUR OR FIVE CHARACTERS
		SELECT * FROM STUDENT
		WHERE FIRSTNAME LIKE '____' OR FIRSTNAME LIKE '_____'
