--LAB 7 (PERFORM SQL QUERIES FOR AGGERATE FUNCTION AND GROUP BY (WITHOUT HAVING) )

--PART – A:

--CREATE TABLE AND INSET RECORDS AS PER BELOW.	

	CREATE TABLE EMP
	(
		EID INT,
		ENAME VARCHAR(25),
		DEPARTMENT VARCHAR(25),
		SALARY INT,
		JOINGDATE DATETIME,
		CITY VARCHAR(25)
	);

	INSERT INTO EMP VALUES
		(101,'RAHUL','ADMIN',56000,'1990-1-1','RAJKOT'),
		(102,'HARDIK','IT',18000,'1990-9-1','AHMEDABAD'),
		(103,'BHAVIN','HR',25000,'1991-5-1','BARODA'),
		(104,'BHOOMI','ADMIN',39000,'1991-2-1','RAJKOT'),
		(105,'ROHIT','IT',17000,'1990-7-1','JAMNAGAR'),
		(106,'PRIYA','IT',9000,'1990-10-1','AHMEDABAD'),
		(107,'BHOOMI','HR',34000,'1991-12-1','RAJKOT')

		TRUNCATE TABLE EMP

	
	SELECT * FROM EMP

	--1. DISPLAY THE HIGHEST, LOWEST, LABEL THE COLUMNS MAXIMUM, MINIMUM RESPECTIVELY.
		SELECT MAX(SALARY) AS MAXIMUM,MIN(SALARY) AS MINIMUM FROM EMP

	--2. DISPLAY TOTAL, AND AVERAGE SALARY OF ALL EMPLOYEES. LABEL THE COLUMNS TOTAL_SAL AND AVERAGE_SAL,RESPECTIVELY.
		SELECT SUM(SALARY) AS TOTAL_SAL,AVG(SALARY) AS AVERAGE_SAL FROM EMP

	--3. FIND TOTAL NUMBER OF EMPLOYEES OF EMPLOYEE TABLE.
		SELECT COUNT(EID) AS NO_OF_EMP FROM EMP

	--4. FIND HIGHEST SALARY FROM RAJKOT CITY.
		SELECT MAX(SALARY) AS HIGHEST_SAL_RAJ
		FROM EMP
		WHERE CITY = 'RAJKOT'

	--5. GIVE MAXIMUM SALARY FROM IT DEPARTMENT.
		SELECT MAX(SALARY) AS HIGHEST_SAL_RAJ
		FROM EMP
		WHERE DEPARTMENT = 'IT'

	--6. COUNT EMPLOYEE WHOSE JOINING DATE IS AFTER 8-FEB-91.
		SELECT COUNT(EID)
		FROM EMP
		WHERE JOINGDATE > '1991-2-8'

	--7. DISPLAY AVERAGE SALARY OF ADMIN DEPARTMENT.
		SELECT AVG(SALARY) AS AVG_ADMIN     
		FROM EMP
		WHERE DEPARTMENT = 'ADMIN'

	--8. DISPLAY TOTAL SALARY OF HR DEPARTMENT.
		SELECT SUM(SALARY) AS TOTAL_SALARY
		FROM EMP
		WHERE DEPARTMENT = 'HR'

	--9. COUNT TOTAL NUMBER OF CITIES OF EMPLOYEE WITHOUT DUPLICATION.
		SELECT COUNT(DISTINCT(CITY)) AS NO_OF_CITY_WITHOUT_DUPLICATION
		FROM EMP
	
	--10. COUNT UNIQUE DEPARTMENTS.
		SELECT COUNT(DISTINCT(DEPARTMENT)) AS DISTINCT_DEPARTMENT
		FROM EMP 

	--11. GIVE MINIMUM SALARY OF EMPLOYEE WHO BELONGS TO AHMEDABAD.
		SELECT MIN(SALARY) AS MINIMUM_AHM
		FROM EMP
		WHERE CITY = 'AHMEDABAD'
	
	--12. FIND CITY WISE HIGHEST SALARY.
		SELECT CITY,MAX(SALARY) AS MAXMINIM_CITY
		FROM EMP
		WHERE CITY = 'AHMEDABAD'	

	--13. FIND DEPARTMENT WISE LOWEST SALARY.
		SELECT DEPARTMENT,MIN(SALARY) 
		FROM EMP 
		GROUP BY DEPARTMENT	

	--14. DISPLAY CITY WITH THE TOTAL NUMBER OF EMPLOYEES BELONGING TO EACH CITY.
		SELECT CITY,COUNT(EID)
		FROM EMP
		GROUP BY CITY

	--15. GIVE TOTAL SALARY OF EACH DEPARTMENT OF EMP TABLE.
		SELECT DEPARTMENT,SUM(SALARY)
		FROM EMP
		GROUP BY DEPARTMENT
	--16. GIVE AVERAGE SALARY OF EACH DEPARTMENT OF EMP TABLE WITHOUT DISPLAYING THE RESPECTIVE DEPARTMENT NAME.
		SELECT AVG(SALARY) AS AVG_SALARY
		FROM EMP
		GROUP BY DEPARTMENT

--PART – B:

	--1. COUNT THE NUMBER OF EMPLOYEES LIVING IN RAJKOT.
		SELECT COUNT(EID) AS NO_OF_EMP
		FROM EMP
		WHERE CITY = 'RAJKOT'

	--2. DISPLAY THE DIFFERENCE BETWEEN THE HIGHEST AND LOWEST SALARIES. LABEL THE COLUMN DIFFERENCE.
		SELECT ( MAX(SALARY) - MIN(SALARY) ) AS DIFFERENCE
		FROM EMP

	--3. DISPLAY THE TOTAL NUMBER OF EMPLOYEES HIRED BEFORE 1ST JANUARY, 1991.
		SELECT COUNT(EID) 
		FROM EMP
		WHERE JOINGDATE < '1991-1-1'
	
--PART – C:

	--1. COUNT THE NUMBER OF EMPLOYEES LIVING IN RAJKOT OR BARODA.
		SELECT COUNT(EID)
		FROM EMP
		WHERE CITY = 'RAJKOT' OR CITY = 'BARODA' 

	--2. DISPLAY THE TOTAL NUMBER OF EMPLOYEES HIRED BEFORE 1ST JANUARY, 1991 IN IT DEPARTMENT.
		SELECT COUNT(EID) 
		FROM EMP
		WHERE JOINGDATE < '1991-1-1' AND DEPARTMENT = 'IT'

	--3. FIND THE JOINING DATE WISE TOTAL SALARIES.
		SELECT JOINGDATE,SUM(SALARY) AS TOTAL_SALARY
		FROM EMP
		GROUP BY JOINGDATE
	
	--4. FIND THE MAXIMUM SALARY DEPARTMENT & CITY WISE IN WHICH CITY NAME STARTS WITH ‘R’.
		SELECT CITY,DEPARTMENT,MIN(SALARY)
		FROM EMP
		WHERE CITY LIKE 'R%'
		GROUP BY DEPARTMENT,CITY