----LAB 9 (PERFORM SQL QUERIES FOR SET OPERATOR AND, SUBQUERIES)

----SUB QUERIES

--PART – A:

	--TABLE STUDENT_DATA

	CREATE TABLE STUDENT_DATA 
	(
		NO INT,
		NAME VARCHAR(25),
		CITY VARCHAR(25),
		DID INT,
	);


	INSERT INTO STUDENT_DATA VALUES
		(101,'RAJU','RAJKOT',10),
		(102,'AMIT','AHMEDABAD',20),
		(103,'SANJAY','BARODA',40),
		(104,'NEHA','RAJKOT',20),
		(105,'MEERA','AHMEDABAD',30),	
		(106,'MAHESH','BARODA',10)

	SELECT * FROM STUDENT_DATA


	--TABLE ACADEMIC

	CREATE TABLE ACADEMIC 
	(
		RNO  INT,
		SPI DECIMAL(4,2),
		BKLOG INT,
	);

	INSERT INTO ACADEMIC VALUES
		(101,8.8,0),
		(102,9.2,2),
		(103,7.6,1),
		(104,8.2,4),
		(105,7.0,2),
		(106,8.9,3)

	SELECT * FROM ACADEMIC

	--TABLE DEPARTMENT

	CREATE TABLE DEPARTMENT
	(
		DID INT,
		DNAME VARCHAR(25)
	);

	INSERT INTO DEPARTMENT VALUES
		(10,'COMPUTER'),
		(20,'ELECTRICAL'),
		(30,'MECHANICAL'),
		(40,'CIVIL')

	SELECT * FROM DEPARTMENT


	--1. DISPLAY DETAILS OF STUDENTS WHO ARE FROM COMPUTER DEPARTMENT.

	--2. DISPLAYS NAME OF STUDENTS WHOSE SPI IS MORE THAN 8.

	--3. DISPLAY DETAILS OF STUDENTS OF COMPUTER DEPARTMENT WHO BELONGS TO RAJKOT CITY.

	--4. FIND TOTAL NUMBER OF STUDENTS OF ELECTRICAL DEPARTMENT.

	--5. DISPLAY NAME OF STUDENT WHO IS HAVING MAXIMUM SPI.

	--6. DISPLAY DETAILS OF STUDENTS HAVING MORE THAN 1 BACKLOG.

--PART – B:


	--1. DISPLAY NAME OF STUDENTS WHO ARE EITHER FROM COMPUTER DEPARTMENT OR FROM MECHANICAL DEPARTMENT.

	--2. DISPLAY NAME OF STUDENTS WHO ARE IN SAME DEPARTMENT AS 102 STUDYING IN.

--PART – C:


	--1. DISPLAY NAME OF STUDENTS WHOSE SPI IS MORE THAN 9 AND WHO IS FROM ELECTRICAL DEPARTMENT.

	--2. DISPLAY NAME OF STUDENT WHO IS HAVING SECOND HIGHEST SPI.

	--3. DISPLAY CITY NAMES WHOSE STUDENTS BRANCH WISE SPI IS 9.2



--SET OPERATORS


--PART – A:


	--CREATE BELOW TWO TABLES AS PER FOLLOWING DATA.


	--1. DISPLAY NAME OF STUDENTS WHO IS EITHER IN COMPUTER OR IN ELECTRICAL.

	--2. DISPLAY NAME OF STUDENTS WHO IS EITHER IN COMPUTER OR IN ELECTRICAL INCLUDING DUPLICATE DATA.

	--3. DISPLAY NAME OF STUDENTS WHO IS IN BOTH COMPUTER AND ELECTRICAL.

	--4. DISPLAY NAME OF STUDENTS WHO ARE IN COMPUTER BUT NOT IN ELECTRICAL.

	--5. DISPLAY NAME OF STUDENTS WHO ARE IN ELECTRICAL BUT NOT IN COMPUTER.

	--6. DISPLAY ALL THE DETAILS OF STUDENTS WHO ARE EITHER IN COMPUTER OR IN ELECTRICAL.

	--7. DISPLAY ALL THE DETAILS OF STUDENTS WHO ARE IN BOTH COMPUTER AND ELECTRICAL.

--PART – B:

	--CREATE BELOW TWO TABLES AS PER FOLLOWING DATA

	--1. DISPLAY NAME OF PERSONS WHO IS EITHER EMPLOYEE OR CUSTOMER.

	--2. DISPLAY NAME OF PERSONS WHO IS EITHER EMPLOYEE OR CUSTOMER INCLUDING DUPLICATE DATA.

	--3. DISPLAY NAME OF PERSONS WHO IS BOTH EMPLOYEE AS WELL AS CUSTOMER.

	--4. DISPLAY NAME OF PERSONS WHO ARE EMPLOYEE BUT NOT CUSTOMER.

	--5. DISPLAY NAME OF PERSONS WHO ARE CUSTOMER BUT NOT EMPLOYEE.

--PART – C:

	--1. PERFORM ALL THE QUERIES OF PART-B BUT DISPLAY ID AND NAME COLUMNS INSTEAD OF NAME ONLY.